language: go

go:
  - 1.8
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
  
script:
  - ./test.sh
  - goveralls -coverprofile=total.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
  