language: go

go:
  - 1.6
  
install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  
script:
  - cd game
  - go test -v -covermode=count -coverprofile=coverage.out .
  - cat coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  - cd ../diag
  - go test -v -covermode=count -coverprofile=coverage.out .
  - cat coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
  